<script setup lang="ts">
import schemaJson from '../../data/schema.json'
import type { SchemaReference } from '~/types/defs'

/**
 * The catalog's JSON Schemas, one table per type.
 *
 * Generated by scripts/prepare-schema.ts rather than written here, so a field
 * added upstream documents itself on the next build. The guide explains what
 * the vocabulary means; this page is the exhaustive list of what a document may
 * contain.
 */
const reference = schemaJson as unknown as SchemaReference
const repoLink = useRepoLink()

useSeo({
	title: 'Schema reference',
	description: 'Every field of the PinMAME machine definition and controller profile formats: types, '
		+ 'enum values, constraints and which are required. Generated from the JSON Schemas themselves.',
})

const documents = reference.documents

const totals = computed(() => ({
	types: documents.reduce((sum, doc) => sum + doc.types.length, 0),
	fields: documents.reduce((sum, doc) => sum + doc.types.reduce((n, type) => n + type.fields.length, 0), 0),
}))

const KIND_LABEL: Record<string, string> = {
	root: 'document root',
	union: 'one of',
	scalar: 'value',
	object: '',
}
</script>

<template>
	<div class="mx-auto max-w-[100rem] px-4 py-8 sm:px-6">
		<header class="mb-10 max-w-3xl">
			<h1 class="text-2xl font-semibold tracking-tight sm:text-3xl">
				Schema reference
			</h1>
			<p class="mt-3 text-[15px] leading-relaxed text-ink-2">
				Every field of every type in the catalog's formats — <span class="num">{{ totals.types }}</span> types,
				<span class="num">{{ totals.fields }}</span> fields. Generated from the JSON Schemas on each build, so this
				page cannot drift from the files it describes.
			</p>
			<p class="mt-3 text-[15px] leading-relaxed text-ink-3">
				For what the vocabulary <em>means</em> — bindings, polarity, coverage, evidence precedence —
				read <NuxtLink to="/guide" class="text-amber hover:underline">the guide</NuxtLink> instead.
			</p>
		</header>

		<div class="grid gap-10 xl:grid-cols-[15rem_minmax(0,1fr)]">
			<aside class="hidden xl:block">
				<nav class="sticky top-20 max-h-[calc(100vh-6rem)] space-y-4 overflow-y-auto pr-2">
					<div v-for="doc in documents" :key="doc.id">
						<p class="eyebrow mb-1.5 px-2.5">
							{{ doc.title }}
						</p>
						<a
							v-for="type in doc.types"
							:key="type.id"
							:href="`#${type.id}`"
							class="num block truncate rounded-lg px-2.5 py-1 text-[12px] text-ink-3 transition-colors hover:bg-raised hover:text-ink"
						>{{ type.name }}</a>
					</div>
				</nav>
			</aside>

			<div class="min-w-0 space-y-14">
				<section v-for="doc in documents" :key="doc.id" class="space-y-6">
					<header class="max-w-3xl">
						<h2 class="text-xl font-semibold tracking-tight">
							{{ doc.title }}
						</h2>
						<p class="mt-2 text-[15px] leading-relaxed text-ink-2">
							{{ doc.blurb }}
						</p>
						<a
							:href="repoLink.file(doc.path)"
							target="_blank"
							rel="noopener noreferrer"
							class="num mt-3 inline-flex items-center gap-1.5 text-[13px] text-ink-3 transition-colors hover:text-amber"
						>
							<Icon name="lucide:file-code-2" class="size-3.5" />
							{{ doc.path }}
							<Icon name="lucide:arrow-up-right" class="size-3" />
						</a>
					</header>

					<article
						v-for="type in doc.types"
						:id="type.id"
						:key="type.id"
						class="panel scroll-mt-20 overflow-hidden"
					>
						<header class="border-b border-line px-4 py-3">
							<div class="flex flex-wrap items-baseline gap-x-3 gap-y-1">
								<h3 class="num text-[15px] font-semibold text-amber">
									{{ type.name }}
								</h3>
								<span v-if="KIND_LABEL[type.kind]" class="eyebrow">{{ KIND_LABEL[type.kind] }}</span>
							</div>

							<p v-if="type.description" class="mt-2 max-w-3xl text-[13px] leading-relaxed text-ink-2">
								{{ type.description }}
							</p>

							<p v-if="type.usedBy.length" class="mt-2 flex flex-wrap items-baseline gap-x-1.5 gap-y-1 text-[12px] text-ink-4">
								<span>Used by</span>
								<a
									v-for="(use, index) in type.usedBy"
									:key="`${use.link}-${use.field}`"
									:href="`#${use.link}`"
									class="num text-ink-3 transition-colors hover:text-amber"
								>{{ use.type }}.{{ use.field }}{{ index < type.usedBy.length - 1 ? ',' : '' }}</a>
							</p>
						</header>

						<!-- a definition that only names a value has no fields to table -->
						<div v-if="type.values.length || type.pattern" class="flex flex-wrap items-baseline gap-2 border-b border-line-soft px-4 py-3">
							<span class="eyebrow shrink-0">{{ type.values.length ? 'Values' : 'Pattern' }}</span>
							<code v-if="type.pattern" class="num text-[12px] break-all text-ink-2">{{ type.pattern }}</code>
							<span
								v-for="value in type.values"
								:key="value"
								class="num rounded border border-line px-1.5 py-0.5 text-[11px] text-ink-2"
							>{{ value }}</span>
						</div>

						<div v-if="type.variants.length" class="flex flex-wrap items-baseline gap-2 border-b border-line-soft px-4 py-3">
							<span class="eyebrow shrink-0">One of</span>
							<a
								v-for="variant in type.variants"
								:key="variant.link"
								:href="`#${variant.link}`"
								class="num rounded border border-line px-1.5 py-0.5 text-[11px] text-ink-2 transition-colors hover:border-amber/35 hover:text-amber"
							>{{ variant.name }}</a>
						</div>

						<p
							v-for="rule in type.rules"
							:key="rule"
							class="flex items-start gap-2 border-b border-line-soft px-4 py-2.5 text-[12px] leading-relaxed text-ink-3"
						>
							<Icon name="lucide:asterisk" class="mt-0.5 size-3 shrink-0 text-amber" />
							{{ rule }}
						</p>

						<div v-if="type.fields.length" class="overflow-x-auto">
							<table class="fields w-full min-w-[40rem] text-left text-sm">
								<!-- fixed columns so every type's table lines up with the next -->
								<colgroup>
									<col style="width: 22%">
									<col style="width: 15%">
									<col style="width: 3rem">
									<col>
								</colgroup>
								<thead>
									<tr class="border-b border-line">
										<th class="eyebrow px-4 py-2 font-semibold">
											Field
										</th>
										<th class="eyebrow px-3 py-2 font-semibold">
											Type
										</th>
										<th class="eyebrow px-2 py-2 text-center font-semibold">
											Req
										</th>
										<th class="eyebrow px-4 py-2 font-semibold">
											Notes
										</th>
									</tr>
								</thead>
								<tbody>
									<tr
										v-for="field in type.fields"
										:key="field.name"
										class="border-b border-line-soft align-top last:border-0"
									>
										<td data-col="name" class="num px-4 py-2.5 text-[13px] whitespace-nowrap text-ink">
											{{ field.name }}
										</td>
										<td data-col="type" class="num px-3 py-2.5 text-[12px] whitespace-nowrap text-ink-3">
											<a v-if="field.link" :href="`#${field.link}`" class="transition-colors hover:text-amber">{{ field.type }}</a>
											<span v-else>{{ field.type }}</span>
										</td>
										<td data-col="req" class="px-2 py-2.5 text-center">
											<Icon v-if="field.required" name="lucide:check" class="size-3.5 text-amber" />
											<span v-else class="text-ink-4">·</span>
										</td>
										<td data-col="notes" class="px-4 py-2.5 text-[13px] leading-relaxed text-ink-2">
											<p v-if="field.description">
												{{ field.description }}
											</p>
											<p v-if="field.reference" class="text-ink-3" :class="field.description ? 'mt-1' : ''">
												Holds {{ field.reference }}.
											</p>
											<p v-if="field.values.length" class="mt-1.5 flex flex-wrap gap-1">
												<span
													v-for="value in field.values"
													:key="value"
													class="num rounded border border-line px-1 py-0.5 text-[11px] text-ink-3"
												>{{ value }}</span>
											</p>
											<p v-if="field.constraints.length" class="num mt-1.5 text-[11px] text-ink-4">
												{{ field.constraints.join(' · ') }}
											</p>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</article>
				</section>

				<ContributeCard
					hint="Changing the schema changes this page — it is generated from the files themselves on every deploy. Adding a field means adding it to schemas/machine.schema.json and to the validator that enforces it."
					primary-to="/guide"
					primary-label="Read the guide"
				/>
			</div>
		</div>
	</div>
</template>

<style scoped>
/*
 * Four columns need about 40rem to stay legible, so the table scrolls sideways
 * on a narrow screen — which pushes Notes, the column a reader actually came
 * for, off the edge. Below `sm` the row becomes a small block instead: name,
 * type and required-ness on one line, the note underneath.
 */
@media (max-width: 639px) {
	/* The whole table drops out of table layout — leaving `display: table` on it
	   keeps the column model alive, which re-imposes the narrow Notes column
	   the stacking exists to escape. */
	.fields {
		display: block;
		min-width: 0;
	}

	.fields thead,
	.fields colgroup {
		display: none;
	}

	.fields tbody,
	.fields tr {
		display: block;
	}

	.fields tr {
		padding: 0.65rem 1rem;
	}

	.fields td {
		padding: 0;
	}

	.fields td[data-col='name'],
	.fields td[data-col='type'],
	.fields td[data-col='req'] {
		display: inline-block;
		vertical-align: baseline;
	}

	.fields td[data-col='type'],
	.fields td[data-col='req'] {
		margin-left: 0.5rem;
	}

	.fields td[data-col='notes']:not(:empty) {
		display: block;
		margin-top: 0.3rem;
	}
}
</style>
