"""Pins that `import-legacy` cannot emit a conflict with no resolution path.

A `Resolution path:` sentence is the only part of a conflict a reader can act
on; without one the record asks a future curator to rediscover the question
before they can start on the answer. 26 pathless records reached the repository
this way, so the clause is generated by the importer itself rather than added by
hand afterwards, and this test fails against the behaviour that produced them.

The check runs through `_DeviceBuilder.add` rather than against the helper
string, because what matters is the description the importer actually writes.
"""

from __future__ import annotations

import unittest

from pinmame_game_defs.legacy import _DeviceBuilder


def _two_sources_disagreeing(label_first: str, label_second: str, *, group: str, device: int) -> list[dict[str, object]]:
	"""Drive the importer's own device merge until it emits a label conflict.

	A conflict is only emitted once the existing device carries two source refs,
	which is exactly the platform-record-then-game-record order the importer uses.
	"""
	builder = _DeviceBuilder()
	collection = "inputs" if group.startswith("pinmame.input") else "outputs"
	kind = "switch" if collection == "inputs" else "coil"
	legacy_type = "switch" if collection == "inputs" else "coil"
	for source_id, label in (("legacy.platform.example", label_first), ("legacy.game.example", label_second)):
		builder.add(
			collection=collection,
			record={"id": device, "description": label},
			group=group,
			kind=kind,
			prefix="switch" if collection == "inputs" else "device",
			source_id=source_id,
			locator=f"{source_id}#/0",
			legacy_type=legacy_type,
			binding_by_alias={},
			alias_by_binding={},
		)
	return builder.conflicts


class GeneratedConflictResolutionPathTests(unittest.TestCase):
	def test_a_generated_conflict_carries_a_resolution_path(self) -> None:
		conflicts = _two_sources_disagreeing("Ball Roll Tilt", "Drop Target 2", group="pinmame.input.switch", device=2)
		self.assertEqual(len(conflicts), 1)
		description = conflicts[0]["description"]
		self.assertIn("Legacy sources disagree on label:", description)
		self.assertIn("Resolution path:", description)
		self.assertTrue(description.rstrip().endswith("Unresolved."), description)

	def test_the_resolution_path_names_the_disputed_address(self) -> None:
		"""A generic sentence that omits the address is not actionable."""
		conflicts = _two_sources_disagreeing("ROM Started", "Ted Motor Direction", group="pinmame.output.solenoid", device=19)
		self.assertEqual(len(conflicts), 1)
		description = conflicts[0]["description"]
		self.assertIn("pinmame.output.solenoid 19", description.split("Resolution path:", 1)[1])

	def test_the_original_labels_survive_the_added_clause(self) -> None:
		"""The clause is appended; it never rewrites what the two sources said."""
		conflicts = _two_sources_disagreeing("Tilt", "Top Saucer Kicker", group="pinmame.input.switch", device=7)
		description = conflicts[0]["description"]
		head = description.split("Resolution path:", 1)[0]
		self.assertEqual(head.strip(), "Legacy sources disagree on label: 'Tilt' versus 'Top Saucer Kicker'.")

	def test_two_names_for_one_device_still_emit_nothing(self) -> None:
		"""Adding a resolution path must not resurrect the suppressed records."""
		self.assertEqual(_two_sources_disagreeing("ROM Started", "Game On Relay", group="pinmame.output.solenoid", device=19), [])


if __name__ == "__main__":
	unittest.main()
