"""Removes legacy `conflicts` records that never described a disagreement.

`import-legacy` compared a platform record's generic cabinet label against a
game record's own label for the same address and emitted a conflict whenever the
two strings differed, with no notion of whether they named the same device. That
produced records like `ROM Started` against `Game On Relay` and `Coin Button 1`
against `Coin 1` -- nothing to resolve, and no evidence that could resolve it.

`src/pinmame_game_defs/legacy.py` now applies `_names_one_device` before emitting
anything, so a re-import cannot recreate them. This tool clears the ones already
committed, using **that same function** rather than a second copy of the rule: an
independent reimplementation drifted from it once already, and the direction it
drifted in deletes real conflicts.

Pairs naming genuinely different devices -- `Ball Roll Tilt` against `Drop
Target 2` -- are left alone.

Run with --check to report without writing.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'src'))

from pinmame_game_defs.legacy import _names_one_device  # noqa: E402

_LABEL_PAIR = re.compile(r"'([^']*)' versus '([^']*)'")


def is_label_synonym(conflict: dict) -> bool:
	"""True when this conflict is two names for one device and nothing more."""
	refs = conflict.get('source_refs') or []
	if not refs or not all(str(ref).startswith('legacy.') for ref in refs):
		return False
	match = _LABEL_PAIR.search(conflict.get('description', ''))
	return bool(match) and _names_one_device(match.group(1), match.group(2))


def main() -> int:
	parser = argparse.ArgumentParser()
	parser.add_argument('--check', action='store_true', help='report without writing')
	parser.add_argument('--root', default='.')
	args = parser.parse_args()

	root = Path(args.root)
	removed = 0
	touched: list[Path] = []
	emptied: list[Path] = []

	# Seeds as well as definitions: several machines are generated by a
	# deterministic curator from a pinned seed, and pruning only the output makes
	# that curator's own --check fail on drift it did not cause.
	for path in sorted(root.glob('machines/**/*.json')) + sorted(root.glob('tools/seeds/**/*.json')):
		doc = json.loads(path.read_text(encoding='utf-8'))
		if not isinstance(doc, dict) or not doc.get('conflicts'):
			continue

		kept = [c for c in doc['conflicts'] if not is_label_synonym(c)]
		if len(kept) == len(doc['conflicts']):
			continue

		removed += len(doc['conflicts']) - len(kept)
		touched.append(path)
		doc['conflicts'] = kept

		# `unresolved_conflicts` is only honest while a conflict remains.
		missing = doc.get('coverage', {}).get('missing')
		if not kept and missing and 'unresolved_conflicts' in missing:
			doc['coverage']['missing'] = [m for m in missing if m != 'unresolved_conflicts']
			emptied.append(path)

		if not args.check:
			# newline='' keeps LF on Windows. The repository is LF throughout, and
			# a silent CRLF rewrite would touch every line of every file opened
			# rather than the conflicts actually removed.
			rendered = json.dumps(doc, indent=2, ensure_ascii=False, sort_keys=True) + '\n'
			with path.open('w', encoding='utf-8', newline='') as handle:
				handle.write(rendered)

	print(f'legacy label synonyms removed : {removed}')
	print(f'files touched                 : {len(touched)}')
	print(f'coverage.missing adjusted     : {len(emptied)}')
	for path in emptied:
		print(f'   {path.as_posix()}')
	return 0


if __name__ == '__main__':
	sys.exit(main())
