"""Semantic naming for Tales from the Crypt: stable device IDs, labels, roles and per-device notes.

The printed charts (parsed by ``tftc_manual``) say what the factory called each address. This module
adds the stable semantic ``id`` for each one and the facts the charts do not carry: which printed
names disagree with each other, which addresses are cabinet or unused, and what each switch does in
the retained known-working table. Nothing here is generated from the table's script text.
"""
from __future__ import annotations

# --- Switches ---------------------------------------------------------------------------------
# address -> (stable id suffix, label). The label follows the printed chart; where the chart and the
# Switch Part Numbers table differ the label denotes the device and the disagreement goes in the note.
SWITCHES: dict[int, tuple[str, str]] = {
    1: ("plumb-tilt", "Plumb Tilt"),
    2: ("fourth-coin", "4th Coin"),
    3: ("credit-button", "Credit Button"),
    4: ("right-coin", "Right Coin"),
    5: ("center-coin", "Center Coin"),
    6: ("left-coin", "Left Coin"),
    7: ("slam-tilt", "Slam Tilt"),
    8: ("buy-in-button", "Buy-In Button"),
    9: ("trough-1-left", "Trough #1 Left"),
    10: ("trough-2", "Trough #2"),
    11: ("trough-3", "Trough #3"),
    12: ("trough-4", "Trough #4"),
    13: ("trough-5", "Trough #5"),
    14: ("trough-6", "Trough #6"),
    15: ("trough-7-right", "Trough #7 Right"),
    16: ("shooter-lane", "Shooter Lane"),
    17: ("left-outlane", "Left Outlane"),
    18: ("left-return", "Left Return"),
    19: ("left-slingshot", "Left Slingshot"),
    20: ("left-bottom-3-bank", "Left Bottom 3-Bank"),
    21: ("left-middle-3-bank", "Left Middle 3-Bank"),
    22: ("left-top-3-bank", "Left Top 3-Bank"),
    23: ("left-bottom-orbit", "Left Bottom Orbit"),
    24: ("left-top-orbit", "Left Top Orbit"),
    25: ("right-outlane", "Right Outlane"),
    26: ("right-return", "Right Return"),
    27: ("right-slingshot", "Right Slingshot"),
    28: ("right-bottom-3-bank", "Right Bottom 3-Bank"),
    29: ("right-middle-3-bank", "Right Middle 3-Bank"),
    30: ("right-top-3-bank", "Right Top 3-Bank"),
    31: ("right-bottom-orbit", "Right Bottom Orbit"),
    32: ("right-top-orbit", "Right Top Orbit"),
    33: ("tombstone-up-limit", "Tombstone Up Limit"),
    36: ("tombstone-down-limit", "Tombstone Down Limit"),
    37: ("tombstone-score", "Tombstone Score (Grave-Stone)"),
    38: ("left-vuk", "VUK Left"),
    39: ("captive-ball-target", "Captive Ball Target"),
    40: ("left-spinner", "Left Spinner"),
    41: ("left-drop-target", "Left Drop Target"),
    42: ("middle-drop-target", "Middle Drop Target"),
    43: ("right-drop-target", "Right Drop Target"),
    44: ("left-ramp-enter", "Left Ramp Enter"),
    45: ("left-ramp-middle", "Left Ramp Middle"),
    46: ("right-ramp-enter", "Right Ramp Enter"),
    47: ("right-ramp-exit", "Right Ramp Exit"),
    48: ("right-spinner", "Right Spinner"),
    49: ("left-turbo-bumper", "Left Turbo Bumper"),
    50: ("bottom-turbo-bumper", "Bottom Turbo Bumper"),
    51: ("right-turbo-bumper", "Right Turbo Bumper"),
    52: ("super-vuk-right", "Super VUK Right"),
    53: ("small-trough", "Small Trough"),
    54: ("large-trough", "Large Trough"),
    55: ("power-scoop", "Power Scoop"),
    56: ("middle-spinner", "Middle Spinner"),
    57: ("left-ramp-exit", "Left Ramp Exit"),
    62: ("launch-button", "Launch Button"),
    63: ("left-flipper-copy", "Left Flipper Button Copy (printed Left End of Stroke)"),
    64: ("right-flipper-copy", "Right Flipper Button Copy (printed Right End of Stroke)"),
}
UNUSED_SWITCHES = (34, 35, 58, 59, 60, 61)
CABINET_ROLES = {
    1: "cabinet.tilt", 2: "cabinet.coin", 3: "cabinet.start", 4: "cabinet.coin", 5: "cabinet.coin",
    6: "cabinet.coin", 7: "cabinet.slam-tilt", 8: "cabinet.buy-in", 62: "cabinet.launch",
}
SWITCH_TYPES = {1: "tilt", 7: "tilt", 3: "button", 8: "button", 62: "button"}

# What the retained known-working table does with each switch (script.vbs of the VPW 1.01 table,
# line numbers from the extraction retained under the working root). Used for the device note only.
SCRIPT_NOTES = {
    9: "The table sets it from the Drain kicker (script lines 1893-1894).",
    10: "Kicker sw10, one of the six slanted trough kickers (script lines 1895-1896).",
    11: "Kicker sw11 (script lines 1897-1898).",
    12: "Kicker sw12 (script lines 1899-1900).",
    13: "Kicker sw13 (script lines 1901-1902).",
    14: "Kicker sw14 (script lines 1903-1904); drive 1's SolCallback (kisort) kicks the ball held here toward 15.",
    15: "Kicker sw15 (script lines 1905-1906); the table clears it from drive 2's KickBallToLane (script line 1936).",
    16: "Trigger sw16 in the shooter lane (script lines 2386-2387).",
    17: "Trigger sw17 (script lines 2388-2389).",
    18: "Trigger sw18 (script lines 2390-2391).",
    23: "Trigger sw23 (script lines 2392-2393).",
    24: "Trigger sw24 (script lines 2394-2395).",
    25: "Trigger sw25 (script lines 2396-2397).",
    26: "Trigger sw26 (script lines 2398-2399).",
    31: "Trigger sw31 (script lines 2400-2401).",
    32: "Trigger sw32 (script lines 2402-2403).",
    20: "Wall target sw20 pulses the switch with vpmTimer.PulseSw (script line 2533).",
    21: "Wall target sw21, vpmTimer.PulseSw (script line 2545).",
    22: "Wall target sw22, vpmTimer.PulseSw (script line 2557).",
    28: "Wall target sw28, vpmTimer.PulseSw (script line 2569).",
    29: "Wall target sw29, vpmTimer.PulseSw (script line 2581).",
    30: "Wall target sw30, vpmTimer.PulseSw (script line 2593).",
    37: "Pulsed from the tombstone's rip_Hit when a ball hits it from below (script lines 2668-2685).",
    38: "Kicker-style trigger sw38; drive 6's KickBallUp38 raises the ball out of it (script lines 1985-2030).",
    39: "HitTarget sw39, vpmTimer.PulseSw (script line 2617).",
    40: "Spinner sw40, vpmTimer.PulseSw (script line 2622).",
    41: "Drop target sw41 in the dtBank cvpmDropTarget (script line 1662).",
    42: "Drop target sw42 in the dtBank cvpmDropTarget (script line 1662).",
    43: "Drop target sw43 in the dtBank cvpmDropTarget (script line 1662).",
    44: "Gate sw44, vpmTimer.PulseSw (script line 2406).",
    45: "Trigger sw45 holds the switch while the ball is on it (script lines 2421-2430).",
    46: "Gate sw46, vpmTimer.PulseSw (script line 2407).",
    47: "Trigger sw47 holds the switch while the ball is on it (script lines 2466-2475).",
    48: "Spinner sw48, vpmTimer.PulseSw (script line 2623).",
    49: "Bumper1, vpmTimer.PulseSw(49) (script line 2629).",
    50: "Bumper2, vpmTimer.PulseSw(50) (script line 2641).",
    51: "Bumper3, vpmTimer.PulseSw(51) (script line 2652).",
    52: "Trigger sw52 is the 'Back VUK - From Subway'; drive 7's KickBallUp52 raises the ball out of it (script lines 2055-2110).",
    53: "Trigger sw53 in the 'Subway' (script lines 2032-2039).",
    54: "Trigger sw54 in the 'Subway' (script lines 2041-2048).",
    55: "Kicker sw55; drive 5's ScoopKick ejects it (script lines 2116-2131).",
    56: "Spinner sw56, vpmTimer.PulseSw (script line 2624).",
    57: "Trigger sw57 holds the switch while the ball is on it (script lines 2499-2510).",
    62: "Set from the plunger key and the lock-bar key (script lines 1712 and 1793).",
    8: "Pulsed from the table's keyFront handler (script line 1717).",
    1: "The table's vpmNudge.TiltSwitch (script line 1657).",
}

# --- Lamps ------------------------------------------------------------------------------------
# address -> (stable id suffix, label). Labels follow the chart's printed cell.
LAMPS: dict[int, tuple[str, str]] = {
    1: ("thunderstorm", "Thunder Storm"),
    2: ("skull-crackin", "Skull Crackin'"),
    3: ("door-prize-select", "Door Prize Select"),
    4: ("frightmare-4", "Frightmare (lamp 4)"),
    5: ("psycho-pops", "Psycho Pops"),
    6: ("robbing-the-crypt", "Robbing the Crypt"),
    7: ("extra-ball-lite", "Extra Ball (lamp 7)"),
    8: ("super-guillotine-targets", "Super Guillotine Targets"),
    9: ("werewolf-countdown-9", "Werewolf Count-down (lamp 9)"),
    10: ("video-mode", "Video Mode"),
    11: ("electric-chair", "Electric Chair"),
    12: ("keeper-targets", "Keeper Targets"),
    13: ("scoop", "Scoop"),
    14: ("buy-in-type", "Buy-In Type"),
    15: ("launch", "Launch"),
    16: ("start-button", "Start Button"),
    17: ("outlanes", "Left/Right Outlane"),
    18: ("extra-ball", "Extra Ball (lamp 18)"),
    19: ("skull-crush", "Skull Crush"),
    20: ("keeper-k", "K"),
    21: ("keeper-e-1", "E (lamp 21)"),
    22: ("keeper-e-2", "E (lamp 22)"),
    23: ("collect-creature-feature", "Collect Creature Feature"),
    24: ("monster-jackpot", "Monster Jackpot"),
    25: ("multiball-25", "Multiball (lamp 25)"),
    26: ("returns", "Right/Left Return"),
    27: ("clone", "Clone"),
    28: ("keeper-r", "R"),
    29: ("keeper-e-3", "E (lamp 29)"),
    30: ("keeper-p", "P"),
    31: ("werewolf-countdown-31", "Werewolf Count-down (lamp 31)"),
    32: ("increase-jackpot", "Increase Jackpot"),
    33: ("lite-creature-feature-33", "Lite Creature Feature (lamp 33)"),
    34: ("frightmare-34", "Frightmare (lamp 34)"),
    35: ("increase-double-jackpot", "Increase Double Jackpot"),
    36: ("lite-creature-feature-36", "Lite Creature Feature (lamp 36)"),
    37: ("rats", "Rats"),
    38: ("goblins", "Goblins"),
    39: ("ghosts", "Ghosts"),
    40: ("bats", "Bats"),
    41: ("left-drop-target", "Left Drop Trgt."),
    42: ("middle-drop-target", "Middle Drop Trgt."),
    43: ("right-drop-target", "Right Drop Trgt."),
    44: ("crypt-t", "T"),
    45: ("crypt-p", "P"),
    46: ("crypt-y", "Y"),
    47: ("crypt-r", "R"),
    48: ("crypt-c", "C"),
    49: ("mystery-door-1", "Mystery Door 1"),
    50: ("mystery-door-2", "Mystery Door 2"),
    51: ("mystery-door-3", "Mystery Door 3"),
    52: ("double-jackpot", "Double Jackpot"),
    53: ("living-dead", "Living Dead"),
    54: ("grave-digger", "Grave-digger"),
    55: ("chainsaw-mode", "Chainsaw Mode"),
    56: ("play-the-organ", "Play the Organ"),
    57: ("left-turbo-bumper", "Left Turbo"),
    58: ("bottom-turbo-bumper", "Bottom Turbo"),
    59: ("right-turbo-bumper", "Right Turbo"),
    60: ("jackpot", "Jackpot"),
    61: ("multiball-61", "Multiball (lamp 61)"),
    62: ("left-ramp-enter", "Left Ramp Enter"),
    63: ("right-ramp-enter", "Right Ramp Enter"),
    64: ("axe-tra-ball", "\"Axe-tra\" Ball"),
}
CABINET_LAMPS = {14: "cabinet.buy-in", 16: "cabinet.start"}
# Lamp addresses that the location table prints as two bulbs (``A`` and ``B``) on one address.
TWO_BULB_LAMPS = {17: ("17A", "17B"), 26: ("26A", "26B")}

# --- Right-hand flash lamps ----------------------------------------------------------------------
# drive -> (PLFD, BACK PANEL, INSERT) bulb counts as printed on the Special Coil Wiring Diagram.
FLASHER_COMPOSITION = {
    1: (2, 1, 1), 2: (3, 0, 1), 3: (2, 0, 2), 4: (2, 1, 1),
    5: (3, 0, 1), 6: (2, 1, 1), 7: (3, 1, 0), 8: (2, 1, 1),
}
