"""Semantic naming for The Who's Tommy Pinball Wizard (Data East 1994).

Stable device-ID suffixes and labels chosen by the curator from the manual's switch and lamp tables,
the coil tables and the retained known-working script. The printed wording itself lives in the
excerpts; this module only names the devices.
"""
from __future__ import annotations

# Switch address -> (device-id suffix, label). Labels follow the Switch Part Numbers table.
SWITCHES = {
    1: ("plumb-bob-tilt", "Plumb Bob Tilt"),
    2: ("fourth-coin", "4th Coin"),
    3: ("credit-button", "Credit Button"),
    4: ("right-coin", "Right Coin"),
    5: ("center-coin", "Center Coin"),
    6: ("left-coin", "Left Coin"),
    7: ("slam-tilt", "Slam Tilt"),
    8: ("extra-ball-button", "Extra Ball Button"),
    9: ("trough-1-left", "Ball Trough #1 Left"),
    10: ("trough-2", "Ball Trough #2"),
    11: ("trough-3", "Ball Trough #3"),
    12: ("trough-4", "Ball Trough #4"),
    13: ("trough-5", "Ball Trough #5"),
    14: ("trough-6", "Ball Trough #6"),
    15: ("trough-7-right", "Ball Trough #7 Right"),
    16: ("shooter-lane", "Shooter Lane"),
    17: ("left-slingshot", "Left Slingshot"),
    18: ("right-slingshot", "Right Slingshot"),
    19: ("vuk", "VUK Microswitch"),
    20: ("left-ramp-standup-left", "Left Ramp Stand-Up Left"),
    21: ("left-ramp-standup-right", "Left Ramp Stand-Up Right"),
    22: ("right-ramp-standup", "Right Ramp Stand-Up"),
    23: ("left-scoop", "Left Scoop"),
    24: ("silver-ball-target", "Silver Ball Target"),
    25: ("left-3-bank-bottom", "Left 3-Bank Stand-Up Bottom"),
    26: ("left-3-bank-middle", "Left 3-Bank Stand-Up Middle"),
    27: ("left-3-bank-top", "Left 3-Bank Stand-Up Top"),
    28: ("mirror-up", "Mirror Up"),
    29: ("top-left-rollover", "Top Left Rollover"),
    30: ("right-ramp-enter", "Right Ramp Enter"),
    31: ("mirror-down", "Mirror Down"),
    32: ("mirror-target", "Mirror Target"),
    33: ("right-3-bank-top", "Right 3-Bank Stand-Up Top"),
    34: ("right-3-bank-middle", "Right 3-Bank Stand-Up Middle"),
    35: ("right-3-bank-bottom", "Right 3-Bank Stand-Up Bottom"),
    36: ("left-return-lane", "Left Return Lane"),
    37: ("right-return-lane", "Right Return Lane"),
    38: ("middle-standup", "Middle Stand-Up"),
    39: ("left-spinner", "Left Spinner"),
    40: ("right-spinner", "Right Spinner"),
    41: ("mirror-trough", "Mirror Trough"),
    42: ("skill-trough", "Skill Trough"),
    43: ("captive-ball-target", "Captive Ball Target"),
    47: ("eject", "Eject"),
    48: ("top-right-rollover", "Top Right Rollover"),
    49: ("left-turbo-bumper", "Left Turbo Bumper"),
    50: ("center-turbo-bumper", "Center Turbo Bumper"),
    51: ("right-turbo-bumper", "Right Turbo Bumper"),
    55: ("left-outlane", "Left Outlane"),
    56: ("right-outlane", "Right Outlane"),
    57: ("left-ramp-enter", "Left Ramp Enter"),
    58: ("left-ramp-exit", "Left Ramp Exit"),
    62: ("right-ramp-exit", "Right Ramp Exit"),
    63: ("left-flipper-copy", "Left Flipper (Cabinet)"),
    64: ("right-flipper-copy", "Right Flipper (Cabinet)"),
}
UNUSED_SWITCHES = (44, 45, 46, 52, 53, 54, 59, 60, 61)

# Cabinet and service switches and the role each plays.
CABINET_ROLES = {
    1: "cabinet.tilt", 2: "cabinet.coin", 3: "cabinet.start", 4: "cabinet.coin", 5: "cabinet.coin",
    6: "cabinet.coin", 7: "cabinet.slam-tilt", 8: "cabinet.extra-ball",
}
# Contact construction where the printed description names it: the tilts and buttons, and the two
# parts the Switch Part Numbers table calls a microswitch ("VUK Microswitch", "Eject (Micro Switch)").
SWITCH_TYPES = {1: "tilt", 7: "tilt", 3: "button", 8: "button", 19: "microswitch", 47: "microswitch"}

# Lamp address -> (device-id suffix, label), following the Lamp Matrix location table.
LAMPS = {
    1: ("insert-tommy-t", "Backbox Insert ...T"),
    2: ("grid-christmas", "Grid: Christmas"),
    3: ("grid-cousin-kevin", "Grid: Cousin Kevin"),
    4: ("grid-holiday-camp", "Grid: Holiday Camp"),
    5: ("grid-lite-extra-ball", "Grid: Lite Extra Ball"),
    6: ("grid-silver-ball", "Grid: Silver Ball"),
    7: ("grid-captain-walker", "Grid: Captain Walker"),
    8: ("grid-wizard", "Grid: Wizard"),
    9: ("skill-shot", "Skill Shot"),
    10: ("insert-tommy-o", "Backbox Insert ...O"),
    11: ("grid-smash-the-mirror", "Grid: Smash the Mirror"),
    12: ("grid-fiddle-about", "Grid: Fiddle About"),
    13: ("grid-acid-queen", "Grid: Acid Queen"),
    14: ("grid-theres-a-doctor", "Grid: There's A Doctor"),
    15: ("grid-tommy-scoring", "Grid: Tommy Scoring"),
    16: ("grid-sally-simpson", "Grid: Sally Simpson"),
    17: ("jackpot", "Jackpot"),
    18: ("double-jackpot", "Double Jackpot"),
    19: ("insert-tommy-m1", "Backbox Insert ...M (first M)"),
    20: ("left-ramp-standup-left", "Left Ramp Stand-Up Left"),
    21: ("left-ramp-standup-right", "Left Ramp Stand-Up Right"),
    22: ("ramp-standup-top", "Ramp Stand-Up Top"),
    23: ("extra-ball-button", "Extra Ball Button"),
    24: ("silver-ball", "Silver Ball"),
    25: ("left-3-bank-bottom", "Left 3-Bank Stand-Up Bottom"),
    26: ("left-3-bank-middle", "Left 3-Bank Stand-Up Middle"),
    27: ("left-3-bank-top", "Left 3-Bank Stand-Up Top"),
    28: ("insert-tommy-m2", "Backbox Insert ...M (second M)"),
    29: ("spinner-bonus-left", "Spinner Bonus Left"),
    30: ("extra-ball", "Extra Ball"),
    31: ("light-union-jack-left", "Light Union Jack Left"),
    32: ("genius", "Genius"),
    33: ("right-3-bank-top", "Right 3-Bank Stand-Up Top"),
    34: ("right-3-bank-middle", "Right 3-Bank Stand-Up Middle"),
    35: ("right-3-bank-bottom", "Right 3-Bank Stand-Up Bottom"),
    36: ("mystery", "Mystery"),
    37: ("insert-tommy-y", "Backbox Insert ...Y"),
    38: ("more-time", "More Time"),
    39: ("captain-walker-left", "Captain Walker Left"),
    40: ("captain-walker-right", "Captain Walker Right"),
    41: ("playfield-tommy-t", "Playfield ...T"),
    42: ("playfield-tommy-o", "Playfield ...O"),
    43: ("playfield-tommy-m1", "Playfield ...M (first M)"),
    44: ("playfield-tommy-m2", "Playfield ...M (second M)"),
    45: ("playfield-tommy-y", "Playfield ...Y"),
    46: ("outlanes", "Outlanes"),
    47: ("mirror-multiball", "Mirror Multiball"),
    48: ("shoot-again", "Shoot Again"),
    49: ("left-turbo-bumper", "Left Turbo Bumper"),
    50: ("center-turbo-bumper", "Center Turbo Bumper"),
    51: ("right-turbo-bumper", "Right Turbo Bumper"),
    52: ("spinner-bonus-right", "Spinner Bonus Right"),
    53: ("lite-union-jack-right", "Lite Union Jack Right"),
    54: ("holiday-camp", "Holiday Camp"),
    55: ("return-lanes", "Return Lanes"),
    56: ("airplane", "Airplane"),
    57: ("acid-queen-left", "Acid Queen Left"),
    58: ("acid-queen-center", "Acid Queen Center"),
    59: ("acid-queen-right", "Acid Queen Right"),
    60: ("sally-simpson-left", "Sally Simpson Left"),
    61: ("sally-simpson-right", "Sally Simpson Right"),
    62: ("scoop-multiball", "Scoop Multiball"),
    63: ("collect-union-jack", "Collect Union Jack"),
    64: ("credit-button", "Credit Button"),
}
# The location table marks these as backbox inserts and draws two bulbs for each.
BACKBOX_LAMPS = (1, 10, 19, 28, 37)
# Two-bulb playfield addresses: the location table's "X2" and the drawing's paired balloons.
TWO_BULB_LAMPS = (46, 55)
CABINET_LAMPS = {23: "cabinet.extra-ball-button-lamp", 64: "cabinet.start-button-lamp"}
